trigger:
  branches:
    include:
      - main
      - dev

variables:
  dockerImageName: 'sosokwani/share2teach-backend'
  dockerImageTag: 'latest'
  dockerImageVersion: '$(Build.BuildId)'
  azureResourceGroup: 'rgShare2Teach'
  azureAppService: 'Share2Teach'

stages:
  - stage: Deploy
    jobs:
      - job: DeployToAzure
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --use-device-code
              az webapp config container set --name $(azureAppService) --resource-group $(azureResourceGroup) --docker-custom-image-name $(dockerImageName):$(dockerImageTag)
            displayName: 'Deploy Docker Image to Azure App Service'
