trigger:
  branches:
    include:
      - main
      - dev  # Include this if you want to trigger builds on dev branch

variables:
  dockerImageName: 'sosokwani/share2teach-backend'
  dockerImageTag: 'latest'
  dockerImageVersion: '$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: BuildDockerImage
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build Application'

          - script: docker build -t $(dockerImageName):$(dockerImageTag) -t $(dockerImageName):$(dockerImageVersion) .
            displayName: 'Build Docker Image'

          - task: Docker@2
            inputs:
              command: 'login'
              containerRegistry: 'DockerHub'  # Replace with your Docker Hub service connection name
              username: '$(DOCKER_USERNAME)'
              password: '$(DOCKER_PASSWORD)'
            displayName: 'Login to Docker Hub'

          - task: Docker@2
            inputs:
              command: 'tag'
              containerRegistry: 'DockerHub'
              repository: $(dockerImageName)
              imageName: $(dockerImageName)
              tag: $(dockerImageVersion)
            displayName: 'Tag Docker Image'

          - task: Docker@2
            inputs:
              command: 'push'
              containerRegistry: 'DockerHub'
              repository: $(dockerImageName)
              tag: $(dockerImageVersion)
            displayName: 'Push Docker Image'

  - stage: Deploy
    jobs:
      - job: DeployToAzure
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'AzureSubscription'  # Replace with your Azure service connection name
              appName: 'Share2Teach'  # Replace with your Azure App Service name
              imageName: '$(dockerImageName):$(dockerImageVersion)'
              containerRegistry: 'DockerHub'  # Replace with your Docker Hub service connection name
            displayName: 'Deploy Docker Image to Azure App Service'
