# Docker
# Build and Deploy a Docker image to Azure Web App for Containers
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'share2teach-backend'

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build Application'

          - script: docker build -t $(imageName):$(tag) .
            displayName: 'Build Docker Image'

          - script: docker tag $(imageName):$(tag) $(ACR_NAME).azurecr.io/$(imageName):$(tag)
            displayName: 'Tag Docker Image for ACR'

          - script: docker push $(ACR_NAME).azurecr.io/$(imageName):$(tag)
            displayName: 'Push Docker Image to ACR'