trigger:
- main

variables:
  dockerImageName: 'sosokwani/share2teach-backend'
  dockerImageTag: 'latest'

stages:
  - stage: Build
    jobs:
      - job: BuildDockerImage
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build Application'

          - script: docker build -t $(dockerImageName):$(dockerImageTag) .
            displayName: 'Build Docker Image'

          - task: Docker@2
            inputs:
              command: 'login'
              containerRegistry: 'DockerHub' # Ensure this matches the Docker Hub service connection name
              username: '$(DOCKER_USERNAME)'
              password: '$(DOCKER_PASSWORD)'
            displayName: 'Login to Docker Hub'

          - task: Docker@2
            inputs:
              command: 'tag'
              containerRegistry: 'DockerHub'
              repository: $(dockerImageName)
              imageName: $(dockerImageName)
              tag: $(dockerImageTag)
            displayName: 'Tag Docker Image'

          - task: Docker@2
            inputs:
              command: 'push'
              containerRegistry: 'DockerHub'
              repository: $(dockerImageName)
              tag: $(dockerImageTag)
            displayName: 'Push Docker Image'

  - stage: Deploy
    jobs:
      - job: DeployToAzure
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure for Students' # Replace with your Azure service connection name
              appName: 'Share2Teach'
              imageName: '$(dockerImageName):$(dockerImageTag)'
              containerRegistry: 'DockerHub' # Ensure this matches the Docker Hub service connection name
            displayName: 'Deploy Docker Image to Azure App Service'
