trigger:
  branches:
    include:
      - main
      - dev

variables:
  dockerImageName: 'sosokwani/share2teach-backend'
  dockerImageTag: 'latest'
  dockerImageVersion: '$(Build.BuildId)'
  azureResourceGroup: 'rgShare2Teach'
  azureAppService: 'Share2Teach'

stages:
  - stage: Build
    jobs:
      - job: BuildDockerImage
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Build Application'

          - script: docker build -t $(dockerImageName):$(dockerImageTag) -t $(dockerImageName):$(dockerImageVersion) .
            displayName: 'Build Docker Image'

          - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
            displayName: 'Login to Docker Hub'

          - script: docker tag $(dockerImageName):$(dockerImageVersion) $(dockerImageName):$(dockerImageTag)
            displayName: 'Tag Docker Image'

          - script: docker push $(dockerImageName):$(dockerImageTag)
            displayName: 'Push Docker Image'

  - stage: Deploy
    jobs:
      - job: DeployToAzure
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --use-device-code
              az webapp config container set --name $(azureAppService) --resource-group $(azureResourceGroup) --docker-custom-image-name $(dockerImageName):$(dockerImageTag)
            displayName: 'Deploy Docker Image to Azure App Service'
