POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "userName": "lee23",
  "userLName": "Doe",
  "email": "mxolisi1@gmail.com",
  "password": "password12345"

}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "mxolisi1@gmail.com",
  "password": "password123435"
}

###
GET http://localhost:3000/protected/admin
