name: CI/CD Pipeline - Developer

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install jest
        run: npm install --save-dev jest

      - name: Set Jest permissions
        run: chmod +x node_modules/.bin/jest

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t sosokwani/share2teach-backend:developer .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push sosokwani/share2teach-backend:developer

  deploy_developer:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Azure Kubernetes Service (AKS) credentials
        uses: azure/aks-set-context@v2
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: share2teach-dev-cluster
          resource-group: Share-2-Teach

      - name: Deploy to Kubernetes (Developer)
        run: kubectl apply -f k8s/deployment-developer.yaml
